disabled_rules:
  - line_length
  - file_length
  - type_body_length
  - variable_name
  - function_parameter_count
  - function_body_length
  - weak_delegate
enabled_rules:
  - force_unwrapping
included: # paths to include during linting. `--path` is ignored if present.
  - Echo
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - EchoTests
